app/month_type/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, FloatField, BooleanField, SubmitField


class MonthTypeForm(FlaskForm):
	name_of_type = StringField('Name of type')
	amount_choice = SelectField('Type of amount', choices=[('percent', '%'), ('money', '₴')], validate_choice=False)
	amount = FloatField('Amount')
	is_default = BooleanField('Default')
	is_everyday = BooleanField('Every day')
	# month_plan=IntegerField('Month plan')
	submit = SubmitField('Add')

app/month_type/routes.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import login_required, current_user

from app import db
from app.models import Types_of_month_spend, Users, Month_plans
from app.month_type.forms import MonthTypeForm

month_types = Blueprint('month_types',__name__)


@month_types.route('/planning/monthly/types/all', methods=['GET', 'POST'])
@login_required
def show_all_types():
	page = request.args.get('page', 1, type=int)
	# plans = [plan for plan in Users.query.filter_by(id=current_user.id).first().plans]
	month_types = Types_of_month_spend.query.filter(Types_of_month_spend.month_plan.in_([plan_id.id for plan_id in
																						 [plan for plan in
																						  Users.query.filter_by(
																							  id=current_user.id).first().plans]])).order_by(
		Types_of_month_spend.id.desc()).paginate(page=page, per_page=5)
	return render_template('month_types/month_types_all.html', month_types=month_types)


@month_types.route('/planning/monthly/<int:month_plan_id>/types/new', methods=['GET', 'POST'])
@login_required
def month_type_new(month_plan_id):
	form = MonthTypeForm()
	if form.validate_on_submit():
		month_plan = Month_plans.query.get_or_404(month_plan_id)
		type_income = month_plan.income
		if form.amount_choice.data == 'percent':
			amount_in_percent = form.amount.data
			amount_in_money = type_income * amount_in_percent / 100
		elif form.amount_choice.data == 'money':
			amount_in_money = form.amount.data
			amount_in_percent = amount_in_money / type_income * 100

		monthtype = Types_of_month_spend(name_of_type=form.name_of_type.data,
										 amount_in_percent=round(amount_in_percent, 2),
										 amount_in_money=round(amount_in_money, 2),
										 is_default=form.is_default.data,
										 is_everyday=form.is_everyday.data,
										 month_plan=month_plan_id)

		db.session.add(monthtype)
		if not monthtype.is_everyday:  # currently left amount adds to daily delta flow#todo decide if left amount is adding to month or day
			month_plan.money_for_day -= monthtype.amount_in_money
			month_plan.money_for_month += monthtype.amount_in_money
		db.session.commit()
		flash('Your month plan has been created', 'success')
		return redirect(url_for('month_plans.month_plan_table_test', month_plan_id=month_plan_id))
	return render_template('month_types/create_new_month_type.html', title='New Month Type', form=form, legend='New Month Type')


@month_types.route('/planning/monthly/<int:month_plan_id>/types/<int:month_type_id>')
@login_required
def month_type_single(month_type_id, month_plan_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.home'))
	month_type_expense = Types_of_month_spend.query.get_or_404(month_type_id)
	bla = month_plan_id
	return render_template('month_types/month_type_single.html', title=month_type_expense.name_of_type,
						   month_type=month_type_expense, month_plan_id=bla)


@month_types.route('/planning/monthly/types/<int:month_type_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_month_type(month_type_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.home'))
	month_type_expense = Types_of_month_spend.query.get_or_404(month_type_id)
	db.session.delete(month_type_expense)
	db.session.commit()
	flash('Type has been deleted.', 'success')
	return redirect(url_for('main.home'))


@month_types.route('/planning/monthly/<int:month_plan_id>/types/<int:month_type_id>/delete', methods=['GET', 'POST'])
@login_required
def edit_month_type(month_plan_id, month_type_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.about'))
	month_type_expense = Types_of_month_spend.query.get_or_404(month_type_id)
	form = MonthTypeForm()
	month_plan = Month_plans.query.get_or_404(month_plan_id)
	if form.validate_on_submit():
		type_income = month_plan.income
		if form.amount_choice.data == 'percent':
			amount_in_percent = form.amount.data
			amount_in_money = type_income * amount_in_percent / 100
		elif form.amount_choice.data == 'money':
			amount_in_money = form.amount.data
			amount_in_percent = amount_in_money / type_income * 100

		month_type_expense.name_of_type = form.name_of_type.data
		month_type_expense.amount_in_percent = round(amount_in_percent, 2)
		month_type_expense.amount_in_money = round(amount_in_money, 2)
		month_type_expense.is_default = form.is_default.data
		month_type_expense.is_everyday = form.is_everyday.data
		month_type_expense.month_plan = month_plan_id
		if not month_type_expense.is_everyday:  # currently left amount adds to daily delta flow#todo decide if left amount is adding to month or day
			month_plan.money_for_day -= month_type_expense.amount_in_money
			month_plan.money_for_month += month_type_expense.amount_in_money
		db.session.commit()
		flash('Expense type for month has been edited successfully', 'success')
		return redirect(url_for('month_types.month_type_single', month_type_id=month_type_expense.id, month_plan_id=month_plan.id))
	elif request.method == 'GET':
		form.name_of_type.data = month_type_expense.name_of_type
		form.amount_choice.data = 'money'
		form.amount.data = month_type_expense.amount_in_money
		form.is_everyday.data = month_type_expense.is_everyday
	return render_template('month_types/create_new_month_type.html', title='Edit Month Type', legend='Edit Month Type', form=form,
						   month_plan_id=month_plan.id)


# todo add edit month_type

app/templates/month_types/create_new_month_type.html
{% extends "layout.html" %} {% block content %}
    {% if 'Edit' in legend %}
    <a class="btn btn-outline-primary btn-block" href="{{ url_for('month_plans.month_plan_table_test', month_plan_id=month_plan_id) }}">Back to all types</a>
    {% endif %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.name_of_type.label(class="form-control-label") }} {% if form.name_of_type.errors %} {{ form.name_of_type(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.name_of_type.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.name_of_type(class="form-control form-control-lg") }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.amount_choice.label(class="form-control-label") }} {% if form.amount_choice.errors %} {{ form.amount_choice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.amount_choice.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.amount_choice(class="form-control form-control-lg") }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.amount.label(class="form-control-label") }} {% if form.amount.errors %} {{ form.amount(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.amount.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.amount(class="form-control form-control-lg") }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.is_everyday.label(class="form-control-label") }} {% if form.is_everyday.errors %} {{ form.is_everyday(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.is_everyday.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.is_everyday(class="form-control form-control-lg") }} {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

app/templates/month_types/month_type_single.html
{% extends "layout.html" %} {% block content %}
    <a class="btn btn-outline-primary btn-block" href="{{ url_for('month_plans.month_plan_table_test', month_plan_id=month_plan_id) }}">
        Back to month plan
    </a>
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <div>
                    <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('month_types.edit_month_type', month_plan_id=month_plan_id, month_type_id=month_type.id) }}">
                            Edit
                    </a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                        Delete
                    </button>
                </div>

            </div>
            <h2>
                <a class="article-title">
                    {{ month_type.name_of_type }}
                </a>
            </h2>
            <p class="article-content">
                {{ month_type.amount_in_percent }} % or {{ month_type.amount_in_money }} ₴
            </p>

        </div>
        <a>
            <small class="text-muted">
                {% if month_type.is_everyday %}
                    Spends everyday
                {% else %}
                    Spends once a month
                {% endif %}
            </small>
        </a>

    </article>
    <!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Purchase?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('month_types.delete_month_type', month_type_id=month_type.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/month_types/month_types_all.html
{% extends "layout.html" %} {% block content %}
    {% for  test in month_types.items%}
        <h1>{{ test.name_of_type }}</h1>
        <p>{{ test.amount_in_percent }}</p>
        <p>{{ test.amount_in_money }}</p>
        <p>{{ test.default }}</p>
        <p>{{ test.is_everyday }}</p>
        <p>{{ test.month_plan }}</p>

    {% endfor %}


{% for page_num in month_types.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} {% if page_num %} {% if month_types.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('month_types.show_all_types', page=page_num) }}">{{ page_num }}</a> {% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('month_types.show_all_types', page=page_num) }}">{{ page_num }}</a> {% endif %} {% else %} ... {% endif %} {% endfor %} {% endblock content %}