app/month_plan/forms.py
from calendar import monthrange
from datetime import datetime

from dateutil.utils import today
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import FloatField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, ValidationError

from app.models import Month_plans


class MonthPlanForm(
	FlaskForm):  # todo rethink the validation because it prevents from editing the month plan| dynamic validation
	month = DateField('Month', validators=[DataRequired()], default=today)
	income = FloatField('Income', validators=[DataRequired()])  # todo check if DecimalField on phone is more accurate
	submit = SubmitField('Add')

	def validate_month(self, month):
		date_from_form = month.data
		if date_from_form:
			comparable_date_start = datetime.strptime('01.' + f'{date_from_form.month}.{date_from_form.year}',
													  '%d.%m.%Y').date()
			comparable_date_end = datetime.strptime(
				f'{monthrange(date_from_form.year, date_from_form.month)[1]}.{date_from_form.month}.{date_from_form.year}',
				'%d.%m.%Y').date()
			month_date = Month_plans.query.filter_by(user_id=current_user.id).filter(
				Month_plans.month >= comparable_date_start, Month_plans.month <= comparable_date_end).first()
			if month_date:
				raise ValidationError(
					'You already have a plan for this month')

app/delta_flow/routes.py
from calendar import monthrange
from datetime import datetime
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user

from app.helper.daily_plan_table import delta_flow_test
from app.models import Spendings, Month_plans

delta_flows = Blueprint('delta_flows', __name__)


@delta_flows.route('/planning/daily/delta_flow',
				   methods=['GET', 'POST'])
@login_required
def delta_flow():
	start_checkpoint = datetime.strptime('01.09.2021', '%d.%m.%Y').date()  # todo create form to choose date
	next_checkpoint = datetime.strptime('30.09.2021',
										'%d.%m.%Y').date()  # todo maybe add formFIELDS to choose date with button to redirect to itself on top of the delta

	bla = Spendings.query.filter_by(user_id=current_user.id).filter(Spendings.day >= start_checkpoint,
																	Spendings.day <= next_checkpoint)  # todo change to normal name

	month_plan_id = 1
	month_plan_delta = Month_plans.query.get_or_404(
		month_plan_id)  # todo think about an actual way to obtain month_id| should it be passed or queued in some way?
	b = month_plan_delta.money_for_day

	a = delta_flow_test(start_checkpoint, next_checkpoint, bla, month_plan_delta.money_for_day)

	return render_template('delta_flow.html', delta_flow_results=a,
						   start_checkpoint=start_checkpoint.strftime("%d.%m.%y"),
						   next_checkpoint=next_checkpoint.strftime("%d.%m.%y"),
						   prev_checkpoint=b)  # todo check naming #todo format dates to human-friendly


@delta_flows.route('/planning/daily/delta_flow/test',
				   methods=['GET', 'POST'])
@login_required
def delta_flow_month():
	month_plan_id = request.args.get('month_plan_id')
	month_plan_delta = Month_plans.query.get_or_404(month_plan_id)
	start_checkpoint = datetime.strptime('01.' + f'{month_plan_delta.month.month}.{month_plan_delta.month.year}',
										 '%d.%m.%Y').date()  # todo create form to choose date
	next_checkpoint = datetime.strptime(
		f'{monthrange(month_plan_delta.month.year, month_plan_delta.month.month)[1]}.{month_plan_delta.month.month}.{month_plan_delta.month.year}',
		'%d.%m.%Y').date()  # todo maybe add formFIELDS to choose date with button to redirect to itself on top of the delta
	bla = Spendings.query.filter_by(user_id=current_user.id).filter(Spendings.day >= start_checkpoint,
																	Spendings.day <= next_checkpoint)  # todo change to normal name

	b = month_plan_delta.money_for_day

	a = delta_flow_test(start_checkpoint, next_checkpoint, bla, month_plan_delta.money_for_day)

	return render_template('delta_flow.html', delta_flow_results=a, start_checkpoint=start_checkpoint,
						   next_checkpoint=next_checkpoint,
						   prev_checkpoint=b)  # todo check naming #todo format dates to human-friendly

app/month_plan/routes.py
from calendar import monthrange

from flask import Blueprint, request, render_template, flash, url_for, redirect
from flask_login import login_required, current_user

from app import db
from app.helper.month_plan_table import plan_to_dict, daily_overall_dict
from app.helper.name_months import months_names
from app.models import Month_plans
from app.month_plan.forms import MonthPlanForm

month_plans = Blueprint('month_plans',__name__)


@month_plans.route('/planning/monthly/months', methods=['GET', 'POST'])
@login_required
def show_all_months():
	page = request.args.get('page', 1, type=int)
	month_plans = Month_plans.query.filter_by(user_id=current_user.id).order_by(Month_plans.month.desc()).paginate(
		page=page, per_page=5)
	return render_template('month_plans/monthplanning.html', month_plans=month_plans, myfunction=months_names)


@month_plans.route('/planning/monthly/new', methods=['GET', 'POST'])
@login_required
def month_plan_new():
	form = MonthPlanForm()
	if form.validate_on_submit():
		monthplan = Month_plans(month=form.month.data,
								income=form.income.data,
								money_for_month=0,
								# todo change 0 to actual value calculated by plan| maybe add more if-coditions to calculate values properly?
								money_for_day=form.income.data,
								user_id=current_user.id)
		db.session.add(monthplan)
		db.session.commit()
		flash('Your month plan has been created', 'success')
		return redirect(url_for('month_plans.show_all_months'))
	return render_template('month_plans/create_new_month_plan.html', title='New Month Plan', form=form, legend='New Month Plan')


@month_plans.route('/planning/monthly/<int:month_plan_id>',
		   methods=['GET', 'POST'])
@login_required
def month_plan_table_test(month_plan_id):
	month_plan = Month_plans.query.get_or_404(month_plan_id)
	days = monthrange(month_plan.month.year, month_plan.month.month)[1]

	return render_template('month_plans/month_plan.html', title=str(month_plan.month.month) + '.' + str(month_plan.month.year),
						   month_plan=month_plan, legend='TEST LEGEND FOR MONTH PLAN',
						   planDictionary=plan_to_dict(month_plan), days=days,
						   monthOverall=daily_overall_dict(plan_to_dict(month_plan), month_plan.income))


@month_plans.route('/planning/monthly/<int:month_plan_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_month_plan(month_plan_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.about'))
	month_plan = Month_plans.query.get_or_404(month_plan_id)
	db.session.delete(month_plan)
	db.session.commit()
	flash('Month plan deleted successfully', 'success')
	return redirect(url_for('month_plans.show_all_months'))


@month_plans.route('/planning/monthly/<int:month_plan_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_month_plan(month_plan_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.about'))
	month_plan = Month_plans.query.get_or_404(month_plan_id)
	form = MonthPlanForm()
	if form.validate_on_submit():
		month_plan.month = form.month.data
		month_plan.income = form.income.data
		db.session.commit()
		flash('Month plan has been edited successfully', 'success')
		return redirect(url_for('month_plans.month_plan_table_test', month_plan_id=month_plan.id))
	elif request.method == 'GET':
		form.month.data = month_plan.month
		form.income.data = month_plan.income
	return render_template('month_plans/create_new_month_plan.html', title='Edit Month Plan', legend='Edit Month Plan', form=form)

app/month_type/routes.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import login_required, current_user

from app import db
from app.models import Types_of_month_spend, Users, Month_plans
from app.month_type.forms import MonthTypeForm

month_types = Blueprint('month_types',__name__)


@month_types.route('/planning/monthly/types/all', methods=['GET', 'POST'])
@login_required
def show_all_types():
	page = request.args.get('page', 1, type=int)
	# plans = [plan for plan in Users.query.filter_by(id=current_user.id).first().plans]
	month_types = Types_of_month_spend.query.filter(Types_of_month_spend.month_plan.in_([plan_id.id for plan_id in
																						 [plan for plan in
																						  Users.query.filter_by(
																							  id=current_user.id).first().plans]])).order_by(
		Types_of_month_spend.id.desc()).paginate(page=page, per_page=5)
	return render_template('month_types/month_types_all.html', month_types=month_types)


@month_types.route('/planning/monthly/<int:month_plan_id>/types/new', methods=['GET', 'POST'])
@login_required
def month_type_new(month_plan_id):
	form = MonthTypeForm()
	if form.validate_on_submit():
		month_plan = Month_plans.query.get_or_404(month_plan_id)
		type_income = month_plan.income
		if form.amount_choice.data == 'percent':
			amount_in_percent = form.amount.data
			amount_in_money = type_income * amount_in_percent / 100
		elif form.amount_choice.data == 'money':
			amount_in_money = form.amount.data
			amount_in_percent = amount_in_money / type_income * 100

		monthtype = Types_of_month_spend(name_of_type=form.name_of_type.data,
										 amount_in_percent=round(amount_in_percent, 2),
										 amount_in_money=round(amount_in_money, 2),
										 is_default=form.is_default.data,
										 is_everyday=form.is_everyday.data,
										 month_plan=month_plan_id)

		db.session.add(monthtype)
		if not monthtype.is_everyday:  # currently left amount adds to daily delta flow#todo decide if left amount is adding to month or day
			month_plan.money_for_day -= monthtype.amount_in_money
			month_plan.money_for_month += monthtype.amount_in_money
		db.session.commit()
		flash('Your month plan has been created', 'success')
		return redirect(url_for('month_plans.month_plan_table_test', month_plan_id=month_plan_id))
	return render_template('month_types/create_new_month_type.html', title='New Month Type', form=form, legend='New Month Type')


@month_types.route('/planning/monthly/<int:month_plan_id>/types/<int:month_type_id>')
@login_required
def month_type_single(month_type_id, month_plan_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.home'))
	month_type_expense = Types_of_month_spend.query.get_or_404(month_type_id)
	bla = month_plan_id
	return render_template('month_types/month_type_single.html', title=month_type_expense.name_of_type,
						   month_type=month_type_expense, month_plan_id=bla)


@month_types.route('/planning/monthly/types/<int:month_type_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_month_type(month_type_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.home'))
	month_type_expense = Types_of_month_spend.query.get_or_404(month_type_id)
	db.session.delete(month_type_expense)
	db.session.commit()
	flash('Type has been deleted.', 'success')
	return redirect(url_for('main.home'))


@month_types.route('/planning/monthly/<int:month_plan_id>/types/<int:month_type_id>/delete', methods=['GET', 'POST'])
@login_required
def edit_month_type(month_plan_id, month_type_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.about'))
	month_type_expense = Types_of_month_spend.query.get_or_404(month_type_id)
	form = MonthTypeForm()
	month_plan = Month_plans.query.get_or_404(month_plan_id)
	if form.validate_on_submit():
		type_income = month_plan.income
		if form.amount_choice.data == 'percent':
			amount_in_percent = form.amount.data
			amount_in_money = type_income * amount_in_percent / 100
		elif form.amount_choice.data == 'money':
			amount_in_money = form.amount.data
			amount_in_percent = amount_in_money / type_income * 100

		month_type_expense.name_of_type = form.name_of_type.data
		month_type_expense.amount_in_percent = round(amount_in_percent, 2)
		month_type_expense.amount_in_money = round(amount_in_money, 2)
		month_type_expense.is_default = form.is_default.data
		month_type_expense.is_everyday = form.is_everyday.data
		month_type_expense.month_plan = month_plan_id
		if not month_type_expense.is_everyday:  # currently left amount adds to daily delta flow#todo decide if left amount is adding to month or day
			month_plan.money_for_day -= month_type_expense.amount_in_money
			month_plan.money_for_month += month_type_expense.amount_in_money
		db.session.commit()
		flash('Expense type for month has been edited successfully', 'success')
		return redirect(url_for('month_types.month_type_single', month_type_id=month_type_expense.id, month_plan_id=month_plan.id))
	elif request.method == 'GET':
		form.name_of_type.data = month_type_expense.name_of_type
		form.amount_choice.data = 'money'
		form.amount.data = month_type_expense.amount_in_money
		form.is_everyday.data = month_type_expense.is_everyday
	return render_template('month_types/create_new_month_type.html', title='Edit Month Type', legend='Edit Month Type', form=form,
						   month_plan_id=month_plan.id)


# todo add edit month_type

app/templates/month_plans/create_new_month_plan.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.month.label(class="form-control-label") }} {% if form.month.errors %} {{ form.month(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.month.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.month(class="form-control form-control-lg") }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.income.label(class="form-control-label") }} {% if form.income.errors %} {{ form.income(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.income.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.income(class="form-control form-control-lg") }} {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

app/templates/month_plans/month_plan.html
{% extends "layout.html" %} {% block content %}
    <a class="btn btn-outline-primary btn-block" href="{{ url_for('month_plans.show_all_months') }}">Back to all plans</a>
<!-- <article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
           <small class="text-muted">{{ month_plan.month.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2 class="article-title">{{ month_plan.income }}</h2>
        <p class="article-content">{{ month_plan.money_for_day }}</p>
    </div>
    {% for type in month_plan.list_of_planned_spending %}
            <a>{{ type.name_of_type }}</a>
        {% endfor %}

</article>-->
<article class="media content-section">
<div class="media-body">
    <p class="article-content" style="font-size: 1.4rem;float: right;">Income: {{ month_plan.income }}</p>
    <p class="article-content" style="font-size: 1.4rem;float: left;">Days: {{ days }}</p>

    <table class="table">
            <thead>
                <tr class="table-info">
                    <th scope="col">Name</th>
                    <th scope="col">Percent</th>
                    <th scope="col">Daily</th>
                    <th scope="col">Amount</th>

                </tr>
            </thead>
            <tbody>{% for type in planDictionary %}
                <tr>

                    <td>
                        <a class="article-title" href="{{ url_for('month_types.month_type_single', month_type_id=planDictionary[type]['id'],month_plan_id= month_plan.id) }}">
                            {{ planDictionary[type]['name'] }}
                        </a>
                    </td>
                    <td>{{ planDictionary[type]['amount_in_percent'] }} %</td>
                    <td>{% if planDictionary[type]['daily'] %}{{ planDictionary[type]['daily'] }} ₴{% else %}{% endif %}</td>
                    <td>{{ planDictionary[type]['amount_in_money'] }} ₴</td>

                </tr>{% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Overall Day</td>
                <td>{{ monthOverall['overall_day_percent'] }} %</td>
                <td>{{ monthOverall['overall_day_daily'] }} ₴</td>
                <td>{{ monthOverall['overall_day_amount'] }} ₴</td>
            </tr>
            <tr>
                <td>Overall Month</td>
                <td>{{ monthOverall['overall_month_percent'] }} %</td>
                <td> </td>
                <td>{{ monthOverall['overall_month_amount'] }} ₴</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Remains</td>
                <td>{{ monthOverall['left_percent'] }} %</td>
                <td></td>
                <td>{% if monthOverall['left_amount']!=0 %}{{ monthOverall['left_amount'] }}{% else %}{{ month_plan.income }}{% endif %}</td>
            </tr>


            </tbody>
        </table>

    <button type="button" class="btn btn-secondary btn-sm m-1" data-toggle="modal" data-target="#newtypeModal">New Type</button>
    <div>


    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                        Delete Month
                    </button>

        </div>


<p></p>


</div>
</article>
<!--Modal-->
<div class="modal fade" id="newtypeModal" tabindex="-1" role="dialog" aria-labelledby="newtypeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newtypeModalLabel">Create new type?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('month_types.month_type_new', month_plan_id=month_plan.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Create">
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Month?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('month_plans.delete_month_plan', month_plan_id=month_plan.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/month_plans/monthplanning.html
{% extends "layout.html" %} {% block content %}
<button type="button" class="btn btn-secondary btn-sm m-1" data-toggle="modal" data-target="#newplanModal">New Plan</button>
    {% for  test in month_plans.items%}
       <!-- <h2><a class="article-title" href="{{ url_for('month_plans.month_plan_table_test', month_plan_id=test.id) }}">{{ test.month.year }} {{ myfunction(test.month.month) }}</a></h2>
        <p>{{ test.income }}</p>
        <p>{{ test.money_for_month }}</p>
        <p>{{ test.money_for_day }}</p>
        {% for type in test.list_of_planned_spending %}
            <p>{{ type.name_of_type }}</p>
        {% endfor %}-->
           <article class="media content-section"> <div class="media-body">
            <h2><a class="article-title" href="{{ url_for('month_plans.month_plan_table_test', month_plan_id=test.id) }}">{{ test.month.year }} {{ myfunction(test.month.month) }}</a></h2>

            </div>
               <p class="article-content">{{ test.income }} ₴
                   <form action="{{ url_for('delta_flows.delta_flow_month', month_plan_id=test.id) }}" method="POST">
                    <input class="btn btn-secondary btn-sm m-1" type="submit" value="Delta">
                </form>
               </p>
           </article>
    {% endfor %}

<!--Modal-->
<div class="modal fade" id="newplanModal" tabindex="-1" role="dialog" aria-labelledby="newplanModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newplanModalLabel">Create new plan?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('month_plans.month_plan_new') }}" >
                    <input class="btn btn-danger" type="submit" value="Create">
                </form>
            </div>
        </div>
    </div>
</div>

{% for page_num in month_plans.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} {% if page_num %} {% if month_plans.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('month_plans.show_all_months', page=page_num) }}">{{ page_num }}</a> {% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('month_plans.show_all_months', page=page_num) }}">{{ page_num }}</a> {% endif %} {% else %} ... {% endif %} {% endfor %} {% endblock content %}