app/month_plan/forms.py
from calendar import monthrange
from datetime import datetime

from dateutil.utils import today
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import FloatField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, ValidationError

from app.models import Month_plans


class MonthPlanForm(
	FlaskForm):  # todo rethink the validation because it prevents from editing the month plan| dynamic validation
	month = DateField('Month', validators=[DataRequired()], default=today)
	income = FloatField('Income', validators=[DataRequired()])  # todo check if DecimalField on phone is more accurate
	submit = SubmitField('Add')

	def validate_month(self, month):
		date_from_form = month.data
		if date_from_form:
			comparable_date_start = datetime.strptime('01.' + f'{date_from_form.month}.{date_from_form.year}',
													  '%d.%m.%Y').date()
			comparable_date_end = datetime.strptime(
				f'{monthrange(date_from_form.year, date_from_form.month)[1]}.{date_from_form.month}.{date_from_form.year}',
				'%d.%m.%Y').date()
			month_date = Month_plans.query.filter_by(user_id=current_user.id).filter(
				Month_plans.month >= comparable_date_start, Month_plans.month <= comparable_date_end).first()
			if month_date:
				raise ValidationError(
					'You already have a plan for this month')

app/spendings/forms.py
from dateutil.utils import today
from flask_wtf import FlaskForm
from wtforms import StringField, FloatField, SelectField, SubmitField
from wtforms.fields.html5 import DateField, DecimalField
from wtforms.validators import DataRequired


class SpendingForm(FlaskForm):
	day = DateField('Day', validators=[DataRequired()], default=today)
	name_of_item = StringField('Name of item', validators=[DataRequired()])
	# todo possible two fields: regular text and select from database - group by name and count occurencies and sort
	#  by that number#todo autocomplete when possible
	quantity = FloatField('Quantity', validators=[DataRequired()])
	quantity_type = SelectField('Quantity type', choices=['л', 'мл', 'кг', 'г', 'шт'])
	spending_amount = DecimalField('Spending amount', validators=[DataRequired()])
	submit = SubmitField('Add')

app/delta_flow/routes.py
from calendar import monthrange
from datetime import datetime
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user

from app.helper.daily_plan_table import delta_flow_test
from app.models import Spendings, Month_plans

delta_flows = Blueprint('delta_flows', __name__)


@delta_flows.route('/planning/daily/delta_flow',
				   methods=['GET', 'POST'])
@login_required
def delta_flow():
	start_checkpoint = datetime.strptime('01.09.2021', '%d.%m.%Y').date()  # todo create form to choose date
	next_checkpoint = datetime.strptime('30.09.2021',
										'%d.%m.%Y').date()  # todo maybe add formFIELDS to choose date with button to redirect to itself on top of the delta

	bla = Spendings.query.filter_by(user_id=current_user.id).filter(Spendings.day >= start_checkpoint,
																	Spendings.day <= next_checkpoint)  # todo change to normal name

	month_plan_id = 1
	month_plan_delta = Month_plans.query.get_or_404(
		month_plan_id)  # todo think about an actual way to obtain month_id| should it be passed or queued in some way?
	b = month_plan_delta.money_for_day

	a = delta_flow_test(start_checkpoint, next_checkpoint, bla, month_plan_delta.money_for_day)

	return render_template('delta_flow.html', delta_flow_results=a,
						   start_checkpoint=start_checkpoint.strftime("%d.%m.%y"),
						   next_checkpoint=next_checkpoint.strftime("%d.%m.%y"),
						   prev_checkpoint=b)  # todo check naming #todo format dates to human-friendly


@delta_flows.route('/planning/daily/delta_flow/test',
				   methods=['GET', 'POST'])
@login_required
def delta_flow_month():
	month_plan_id = request.args.get('month_plan_id')
	month_plan_delta = Month_plans.query.get_or_404(month_plan_id)
	start_checkpoint = datetime.strptime('01.' + f'{month_plan_delta.month.month}.{month_plan_delta.month.year}',
										 '%d.%m.%Y').date()  # todo create form to choose date
	next_checkpoint = datetime.strptime(
		f'{monthrange(month_plan_delta.month.year, month_plan_delta.month.month)[1]}.{month_plan_delta.month.month}.{month_plan_delta.month.year}',
		'%d.%m.%Y').date()  # todo maybe add formFIELDS to choose date with button to redirect to itself on top of the delta
	bla = Spendings.query.filter_by(user_id=current_user.id).filter(Spendings.day >= start_checkpoint,
																	Spendings.day <= next_checkpoint)  # todo change to normal name

	b = month_plan_delta.money_for_day

	a = delta_flow_test(start_checkpoint, next_checkpoint, bla, month_plan_delta.money_for_day)

	return render_template('delta_flow.html', delta_flow_results=a, start_checkpoint=start_checkpoint,
						   next_checkpoint=next_checkpoint,
						   prev_checkpoint=b)  # todo check naming #todo format dates to human-friendly

app/month_type/routes.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import login_required, current_user

from app import db
from app.models import Types_of_month_spend, Users, Month_plans
from app.month_type.forms import MonthTypeForm

month_types = Blueprint('month_types',__name__)


@month_types.route('/planning/monthly/types/all', methods=['GET', 'POST'])
@login_required
def show_all_types():
	page = request.args.get('page', 1, type=int)
	# plans = [plan for plan in Users.query.filter_by(id=current_user.id).first().plans]
	month_types = Types_of_month_spend.query.filter(Types_of_month_spend.month_plan.in_([plan_id.id for plan_id in
																						 [plan for plan in
																						  Users.query.filter_by(
																							  id=current_user.id).first().plans]])).order_by(
		Types_of_month_spend.id.desc()).paginate(page=page, per_page=5)
	return render_template('month_types/month_types_all.html', month_types=month_types)


@month_types.route('/planning/monthly/<int:month_plan_id>/types/new', methods=['GET', 'POST'])
@login_required
def month_type_new(month_plan_id):
	form = MonthTypeForm()
	if form.validate_on_submit():
		month_plan = Month_plans.query.get_or_404(month_plan_id)
		type_income = month_plan.income
		if form.amount_choice.data == 'percent':
			amount_in_percent = form.amount.data
			amount_in_money = type_income * amount_in_percent / 100
		elif form.amount_choice.data == 'money':
			amount_in_money = form.amount.data
			amount_in_percent = amount_in_money / type_income * 100

		monthtype = Types_of_month_spend(name_of_type=form.name_of_type.data,
										 amount_in_percent=round(amount_in_percent, 2),
										 amount_in_money=round(amount_in_money, 2),
										 is_default=form.is_default.data,
										 is_everyday=form.is_everyday.data,
										 month_plan=month_plan_id)

		db.session.add(monthtype)
		if not monthtype.is_everyday:  # currently left amount adds to daily delta flow#todo decide if left amount is adding to month or day
			month_plan.money_for_day -= monthtype.amount_in_money
			month_plan.money_for_month += monthtype.amount_in_money
		db.session.commit()
		flash('Your month plan has been created', 'success')
		return redirect(url_for('month_plans.month_plan_table_test', month_plan_id=month_plan_id))
	return render_template('month_types/create_new_month_type.html', title='New Month Type', form=form, legend='New Month Type')


@month_types.route('/planning/monthly/<int:month_plan_id>/types/<int:month_type_id>')
@login_required
def month_type_single(month_type_id, month_plan_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.home'))
	month_type_expense = Types_of_month_spend.query.get_or_404(month_type_id)
	bla = month_plan_id
	return render_template('month_types/month_type_single.html', title=month_type_expense.name_of_type,
						   month_type=month_type_expense, month_plan_id=bla)


@month_types.route('/planning/monthly/types/<int:month_type_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_month_type(month_type_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.home'))
	month_type_expense = Types_of_month_spend.query.get_or_404(month_type_id)
	db.session.delete(month_type_expense)
	db.session.commit()
	flash('Type has been deleted.', 'success')
	return redirect(url_for('main.home'))


@month_types.route('/planning/monthly/<int:month_plan_id>/types/<int:month_type_id>/delete', methods=['GET', 'POST'])
@login_required
def edit_month_type(month_plan_id, month_type_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.about'))
	month_type_expense = Types_of_month_spend.query.get_or_404(month_type_id)
	form = MonthTypeForm()
	month_plan = Month_plans.query.get_or_404(month_plan_id)
	if form.validate_on_submit():
		type_income = month_plan.income
		if form.amount_choice.data == 'percent':
			amount_in_percent = form.amount.data
			amount_in_money = type_income * amount_in_percent / 100
		elif form.amount_choice.data == 'money':
			amount_in_money = form.amount.data
			amount_in_percent = amount_in_money / type_income * 100

		month_type_expense.name_of_type = form.name_of_type.data
		month_type_expense.amount_in_percent = round(amount_in_percent, 2)
		month_type_expense.amount_in_money = round(amount_in_money, 2)
		month_type_expense.is_default = form.is_default.data
		month_type_expense.is_everyday = form.is_everyday.data
		month_type_expense.month_plan = month_plan_id
		if not month_type_expense.is_everyday:  # currently left amount adds to daily delta flow#todo decide if left amount is adding to month or day
			month_plan.money_for_day -= month_type_expense.amount_in_money
			month_plan.money_for_month += month_type_expense.amount_in_money
		db.session.commit()
		flash('Expense type for month has been edited successfully', 'success')
		return redirect(url_for('month_types.month_type_single', month_type_id=month_type_expense.id, month_plan_id=month_plan.id))
	elif request.method == 'GET':
		form.name_of_type.data = month_type_expense.name_of_type
		form.amount_choice.data = 'money'
		form.amount.data = month_type_expense.amount_in_money
		form.is_everyday.data = month_type_expense.is_everyday
	return render_template('month_types/create_new_month_type.html', title='Edit Month Type', legend='Edit Month Type', form=form,
						   month_plan_id=month_plan.id)


# todo add edit month_type

app/spendings/routes.py
from datetime import datetime

from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import login_required, current_user

from app import db
from app.helper.spend_validate import validate_spendings
from app.models import Spendings
from app.spendings.forms import SpendingForm

spendings = Blueprint('spendings',__name__)


@spendings.route('/spending/all', methods=['GET', 'POST'])
@login_required
def _spendings():
	page = request.args.get('page', 1, type=int)
	day_spending = Spendings.query.filter_by(user_id=current_user.id).order_by(Spendings.id.desc()).paginate(page=page,
																											 per_page=10)

	return render_template('spendings/spendings.html', day_spending=day_spending)


@spendings.route('/spending/day')
@login_required
def spendings_day():
	a = request.args.get('start_day')  # todo rename variable
	b = request.args.get('day')  # todo rename variable
	c = datetime.strptime(f'{b}.{a[:4]}', '%d.%m.%Y').date()  # todo rename variable

	day_spending = Spendings.query.filter_by(user_id=current_user.id).filter(Spendings.day == c).order_by(
		Spendings.id.desc()).all()
	return render_template('spendings/spendings_day.html', day_spending=day_spending)


@spendings.route('/spending/new', methods=['GET', 'POST'])
@login_required
def new_spending():
	form = SpendingForm()
	if form.validate_on_submit():
		spending = Spendings(day=form.day.data,
							 name_of_item=form.name_of_item.data,
							 quantity=form.quantity.data,
							 quantity_type=form.quantity_type.data,
							 spending_amount=form.spending_amount.data,
							 user_id=current_user.id)
		validate_spendings(spending)
		db.session.add(spending)
		db.session.commit()
		flash('Your spending has been created', 'success')
		return redirect(url_for('main.home'))
	return render_template('spendings/create_new_spending.html', title='New Purchase', form=form, legend='New Purchase')


@spendings.route('/spending/<int:spending_id>')
@login_required
def spending(spending_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.home'))
	spending = Spendings.query.get_or_404(spending_id)
	return render_template('spendings/spending.html', title=spending.name_of_item, purchase=spending)


@spendings.route('/spending/<int:spending_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_spending(spending_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.home'))
	spending = Spendings.query.get_or_404(spending_id)
	db.session.delete(spending)
	db.session.commit()
	flash('Purchase has been deleted!', 'success')
	return redirect(url_for('main.home'))


@spendings.route('/spending/<int:spending_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_spending(spending_id):
	if not current_user.is_authenticated:
		return redirect(url_for('main.home'))
	spending = Spendings.query.get_or_404(spending_id)
	form = SpendingForm()
	if form.validate_on_submit():
		spending.day = form.day.data
		spending.name_of_item = form.name_of_item.data
		spending.quantity = form.quantity.data
		spending.quantity_type = form.quantity_type.data
		spending.spending_amount = form.spending_amount.data

		validate_spendings(spending)

		db.session.commit()
		flash('Purchase has been updated!', 'success')
		return redirect(url_for('spendings.spending', spending_id=spending.id))
	elif request.method == 'GET':
		form.day.data = spending.day
		form.name_of_item.data = spending.name_of_item
		form.quantity.data = spending.quantity
		form.quantity_type.data = spending.quantity_type
		form.spending_amount.data = spending.spending_amount
	return render_template('spendings/create_new_spending.html', title='Edit Purchase', legend='Edit Purchase', form=form)

app/users/routes.py
from flask import Blueprint, redirect, url_for, flash, render_template, request
from flask_login import current_user, login_user, login_required, logout_user

from app import bcrypt, db
from app.models import Users
from app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from app.users.utils import send_reset_email

users = Blueprint('users',__name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(
			form.password.data).decode('utf-8')
		user = Users(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash('Your account has been created! You are now able to log in', 'success')
		return redirect(url_for('users.login'))
	return render_template('users/register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = Users.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Login Unsuccessful. Please check email and password', 'danger')
	return render_template('users/login.html', title='Login', form=form)


@users.route("/logout")
@login_required
def logout():
	logout_user()
	return redirect(url_for('main.home'))



@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	if not current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = UpdateAccountForm()
	if form.validate_on_submit():
		current_user.email = form.email.data
		current_user.username = form.username.data
		db.session.commit()
		flash('Account info has been updated!', 'success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.email.data = current_user.email
		form.username.data = current_user.username
	return render_template('users/account.html', title='Account', form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
	form = RequestResetForm()
	if current_user.is_authenticated:
		form.email.data = current_user.email
	if form.validate_on_submit():
		user = Users.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('Please, check your mailbox and spam folder. Email with instructions has been sent.', 'info')
		return redirect(url_for('users.login'))
	return render_template('users/reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
	# if current_user.is_authenticated:
	# 	return redirect(url_for('main.home'))
	user = Users.verify_reset_token(token)
	if user is None:
		flash('Invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(
			form.password.data).decode('utf-8')
		user.password=hashed_password
		db.session.commit()
		flash('Your password has been changed!', 'success')
		return redirect(url_for('users.login'))
	return render_template('users/reset_token.html', title='Reset Password', form=form)

app/templates/about.html
{% extends "layout.html" %} {% block content %}

<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <h2 class="media-heading">
                User
            </h2>
        </div>
        <p class="article-content">
            Юзер - єдиний спосіб використовувати сайт, тому що усі витрати та плани на місяць підв'язуються до унікального id.
            Тому варто зареєструватися на сайті для подальшого використання. Наразі перевірки email немає, тож можна вводити щось накшталт test@test.com. Головне - запам'ятати. Але перевірка може з'явитися у майбутньому тож раджу використовувати справжній.
            Пароль при реєстрації зашифровується і відомий тільки користувачу.
        </p>
    </div>
</article>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <h2 class="media-heading">
                Home
            </h2>
        </div>
        <p class="article-content">
            Home - головна сторінка сайту, на якій ви можете побачити інформацію по витратам, які ви зробили сьогодні та яким чином вони впливають на ваш бюджет.
            Для того, аби побачити результат <b>необхідно</b> додати план витрат на місяць.
        </p>
    </div>
</article>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <h2 class="media-heading">
                All plans
            </h2>
        </div>
        <p class="article-content">
            All plans - сторінка на якій ви можете додати план витрат на місяць за допомогою кнопки <button type="button" class="btn btn-secondary btn-sm m-1">New Plan</button>
            У цій версії сайту виберіть будь-яку дату всередині місяця для того, аби вибрати безпосередньо місяць та введіть ваш дохід або кількість грошей, яку ви хочете розпланувати
            Натисніть на найменування місяця для подробиць. Приклад: <h2><a class="article-title" href="#">2022 April</a></h2>
            Натисніть на <button type="button" class="btn btn-secondary btn-sm m-1">Delta</button> для перегляду історії витрат за місяць
        </p>
    </div>
</article>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <h2 class="media-heading">
                Month Plan
            </h2>
        </div>
        <p class="article-content">
            Тут відображаються ваші заплановані витрати на місяць та щоденне використання у абслютному значенні та у відсотках до доходу. Гроші виділені на щоденні витрати враховуються при плануванні на сторінці Delta.
            Натисніть на ім'я типу витрат для редагування.

            Додайте типи запланованих витрат за допомогою кнопки <button type="button" class="btn btn-secondary btn-sm m-1">New Type</button>
            Вкажіть ім'я типу витрати, наприклад: комуналка, інвестування, кіно, їжа.
            Вкажіть тип запланованої витрати у відсотках від прибутку чи в абсолютному значенні.
            Вкажіть чи ця витрата запланована на щоденне використання, наприклад: іжа, кіно, транспорт.
            За замовчуванням, залишок незапланованих грошей враховується до щоденного використання у Delta
        </p>
    </div>
</article>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <h2 class="media-heading">
                Delta
            </h2>
        </div>
        <p class="article-content">
            Натисніть на дату для перегляду витрат за день.
            Result - сума витрат за день.
            Balance - кількість грошей виділена на щоденні витрати(Money) поділена на кількість днів, що залишилися до кінця місяця.
            Savings - кількість грошей, яка була збережена.

        </p>
    </div>
</article>
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <h2 class="media-heading">
                Purchase
            </h2>
        </div>
        <p class="article-content">
            Додати витрату можна з декількох сторінок сайту за допомогою кнопки Add purchase.
            Вкажіть дату витрати, за замовчуванням встановлюється поточна дата.
            Вкажіть найменування витрати, наприклад сік.
            Вкажіть кількість продукту.
            Виберіть тип кількості.
            Вкажіть кількість витрачених коштів.
        </p>
    </div>
</article>


{% endblock content %}

app/templates/home.html
{% extends "layout.html" %} {% block content %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <small class="text-muted">
                Today: {{ today_date.strftime('%d.%m.%Y') }}
            </small>
            <div>
                <p class="align-content-start">
                    {{ mid_sum_delta }} ₴ - Saved today
                </p>
            </div>
        </div>
        <p class="article-content">
            {{ dynamic_mid }} ₴ - Money planned for today
            {{ day_sum }} ₴     - Today's result
        </p>
    </div>
    <div>
        <a class="btn btn-outline-primary btn-lg" href="{{ url_for('spendings.new_spending') }}">
            <small class="text-muted">
                Add purchase
            </small>
        </a>
    </div>
</article>
{% if not day_spending %}
    <article class="media content-section">
        No purchases yet
    </article>
{% endif %}
{% for day in  day_spending%}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <div>
                    <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('spendings.edit_spending', spending_id=day.id) }}">
                            Edit
                    </a>

                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                        Delete
                    </button>
                </div>

            </div>
            <h2>
                <a class="article-title" href="{{ url_for('spendings.spending', spending_id=day.id) }}">
                    {{ day.name_of_item }}
                </a>
            </h2>
            <p class="article-content">
                {{ day.quantity }} {{ day.quantity_type }}
            </p>
        </div>
        <a>
            {{ day.spending_amount }} ₴
        </a>
    </article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Purchase?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('spendings.delete_spending', spending_id=day.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock content%}

app/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

    {% if title %}
        <title>Day to Money - {{ title }}</title>
    {% else %}
        <title>Day to Money</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Day to Money</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('main.home') }}">            Home</a>
                  <a class="nav-item nav-link" href="{{ url_for('main.about') }}">           About</a>
                  <a class="nav-item nav-link" href="{{ url_for('spendings._spendings') }}">       Purchases</a>
                  <a class="nav-item nav-link" href="{{ url_for('month_plans.show_all_months') }}"> Plans</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            <!--<a class="nav-item nav-link" href="{{ url_for('month_types.show_all_types') }}">All types</a>-->
            <!--<a class="nav-item nav-link" href="{{ url_for('delta_flows.delta_flow') }}">Delta</a>-->
            {% if current_user.is_authenticated %}
                {% if current_user.status==True %}
                    <a class="nav-item nav-link" href="{{ url_for('spendings.new_spending') }}">  Admin</a>
                {% endif %}
              <a class="nav-item nav-link" href="{{ url_for('spendings.new_spending') }}">        Add purchase</a>
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">              Logout</a>
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}">             Account</a>
            {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row" style="justify-content: center;">
        <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
        </div>
      </div>
    </main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>